# 20250505001

## 问题描述

新建任务窗口，点击“保存”，提示：

```
(base) D:\WorkSpace\PyProjTracker>D:/Users/xkey/anaconda3/python.exe d:/WorkSpace/PyProjTracker/src/MainWindow.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Users\xkey\anaconda3\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "d:\WorkSpace\PyProjTracker\src\MainWindow.py", line 176, in _save
    self._refresh_task_list()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MilestoneWindow' object has no attribute '_refresh_task_list'
```


## 定位过程

## 根因分析

## 修改方案分析

## 合入记录

## 验证过程